### ISSUE TITLE
Individual Assignment Peer Review Feedback

### ISSUE THREAD

**Issue by tieandrews** [tieandrews/fortunato-wheels#1]

**Comment by qurat-azim** [comment]
Awesome app Ty, very nicely done! I see myself using this :)
Just a couple of nitpicks here:
- The tooltip in the prices chart can sometimes show weird things for condition and cylinders. Maybe there's missing info for some cars
- When I select both Honda and Toyota, does the mileage chart returns a stacked chart. It would probably be a good idea to make that clear, or may be unstack them with some lesser opacity level
- The repo has contributing file that links to files in our group suicides app

**Comment by stepanz25** [comment]
I had great pleasure using the application created by Ty. It looks like you have put a lots of work into it, great job. A couple of improvements that you could consider:

- In "Select Model" dropdown menu, I would recommend ordering the list in alphabetical order. This way it would make it easier for the user to find the correct car model they are looking for. Simplify the filter option to make it easier for users to find what they're looking for will make it way more user friendly
- I find it really hard to read the "Vehicle Mileage" bar chart, so I would either consider adding the contour lines to differentiate the bars or separating them which should make it easier for users to differentiate between the different bars and understand the distribution of vehicle mileage better.
- Sometime, even if I don't set up a year or price filters, there is either no or only one data point available. It might be really hard to make a comparison or get a true sense of what the data looks like for those models. So, maybe if there is very limited data available, it is worth considering to exclude it.

I hope to see further improvement and iterations on this project resulting in a more polished and effective tool for buying used cars. Great job!

**Comment by ZilongYi** [comment]
THIS DASHBOARD IS SO COOOOOOL!

Really like the way you setup the dashboard, layout, font, color etc.  Also, you linked your dash back to Plotly. Well done. 

Two modifications might to consider:
1. In the first page, characters in two sub cards are not aligned. It would be aesthetically better if they are aligned. 
2. I noticed that there seems to be no data points for some categories of model. I would say to exclude those options beforehand. 

Oveall, Really nice work. Nicely done
